module.exports = {
  id: {
    type: 'number',
    required: false,
    defaultValue: 0,
    visibility: false,
    name: 'id',
    editable: true,
    inputType: 'hidden',
    label: 'id',
  },
  uid: {
    type: 'number',
    required: false,
    defaultValue: 0,
    visibility: true,
    name: 'id',
    editable: false,
    label: 'id',
  },
  name: {
    type: 'string',
    required: true,
    defaultValue: '',
    visibility: true,
    name: 'name',
    editable: true,
    inputType: 'text',
    label: 'Имя',
    validationRules: {
      type: 'string',
    },
  },
  dateCreated: {
    required: false,
    type: 'string',
    defaultValue: null,
    visibility: true,
    name: 'dateCreated',
    editable: true,
    label: 'Дата создания',
    inputType: 'hidden',
  },
  clientID: {
    type: 'number',
    required: true,
    defaultValue: 0,
    visibility: false,
    name: 'clientID',
    editable: true,
    label: 'Клиент',
    inputType: 'select',
    options: ['clients', 'name'],
    validationRules: {
      type: 'number',
    },
  },
  client: {
    type: 'string',
    required: false,
    defaultValue: null,
    visibility: true,
    name: 'client',
    editable: false,
    label: 'client',
  },
  clients: {
    type: 'object',
    required: false,
    defaultValue: null,
    visibility: false,
    name: 'clients',
    editable: false,
    label: 'clients',
  },
  services: {
    type: 'object',
    required: false,
    defaultValue: [
      {
        id: 0,
        price: 0,
        description: 0,
      },
    ],
    visibility: false,
    name: 'services',
    editable: true,
    label: 'Услуги',
    inputType: 'group',
    isDynamicGroup: true,
    elements: [
      {
        type: 'string',
        required: true,
        defaultValue: 0,
        visibility: true,
        name: 'description',
        editable: true,
        inputType: 'text',
        label: 'Описание',
        validationRules: {
          type: 'string',
        },
      },
      {
        type: 'number',
        required: true,
        defaultValue: 0,
        visibility: true,
        name: 'count',
        editable: true,
        inputType: 'text',
        label: 'Количество',
        validationRules: {
          type: 'number',
        },
      },
      {
        type: 'number',
        required: true,
        defaultValue: 0,
        visibility: true,
        name: 'price',
        editable: true,
        inputType: 'text',
        label: 'Цена',
        validationRules: {
          type: 'number',
        },
      },
    ],
    validationRules: {
      type: 'object',
      minLength: 0,
    },
  },
  pdf: {
    type: 'boolean',
    required: false,
    defaultValue: null,
    visibility: false,
    name: 'pdf',
    editable: false,
    label: 'pdf',
  },
};
